-- scripts/seed_demo_data.sql
-- DEMO DATA (DEV ONLY)
-- Password for ALL users below: admin123

-- ================
-- USERS
-- ================
WITH upserts AS (
  INSERT INTO "dcms_user" (username, display_name, password_hash, roles, is_active)
  VALUES
    -- staff
    ('manager1',   'Clinic Manager',   '$argon2id$v=19$m=65536,t=3,p=4$vl6eGKpf/3SdpXkQ1xYbnQ$8Fx8GG1GiIiqjH881zBdOBVnmpjpgqm8KVz1X5sUIAE', 2, TRUE),
    ('doctor1',    'Dr. Alice',        '$argon2id$v=19$m=65536,t=3,p=4$vl6eGKpf/3SdpXkQ1xYbnQ$8Fx8GG1GiIiqjH881zBdOBVnmpjpgqm8KVz1X5sUIAE', 3, TRUE),
    ('doctor2',    'Dr. Bob',          '$argon2id$v=19$m=65536,t=3,p=4$vl6eGKpf/3SdpXkQ1xYbnQ$8Fx8GG1GiIiqjH881zBdOBVnmpjpgqm8KVz1X5sUIAE', 3, TRUE),
    ('reception1', 'Reception Desk',   '$argon2id$v=19$m=65536,t=3,p=4$vl6eGKpf/3SdpXkQ1xYbnQ$8Fx8GG1GiIiqjH881zBdOBVnmpjpgqm8KVz1X5sUIAE', 4, TRUE),

    -- extra accounts
    ('manager2',   'Manager Two',      '$argon2id$v=19$m=65536,t=3,p=4$vl6eGKpf/3SdpXkQ1xYbnQ$8Fx8GG1GiIiqjH881zBdOBVnmpjpgqm8KVz1X5sUIAE', 2, TRUE),
    ('doctor3',    'Dr. Carol',        '$argon2id$v=19$m=65536,t=3,p=4$vl6eGKpf/3SdpXkQ1xYbnQ$8Fx8GG1GiIiqjH881zBdOBVnmpjpgqm8KVz1X5sUIAE', 3, TRUE),
    ('reception2', 'Reception Two',    '$argon2id$v=19$m=65536,t=3,p=4$vl6eGKpf/3SdpXkQ1xYbnQ$8Fx8GG1GiIiqjH881zBdOBVnmpjpgqm8KVz1X5sUIAE', 4, TRUE)

  ON CONFLICT (username) DO UPDATE
  SET display_name  = EXCLUDED.display_name,
      password_hash = EXCLUDED.password_hash,
      roles         = EXCLUDED.roles,
      is_active     = EXCLUDED.is_active
  RETURNING user_id, username, display_name, roles
)
SELECT 1;

-- ================
-- POSITIONS
-- ================
INSERT INTO position (position_type, display_name, category)
VALUES
  ('ADMIN',     'Administrator', 0),
  ('MANAGER',   'Clinic Manager', 0),
  ('DOCTOR',    'Dentist', 1),
  ('ORTHO',     'Orthodontist', 1),
  ('RECEPTION', 'Receptionist', 2)
ON CONFLICT DO NOTHING;

-- ================
-- EMPLOYEES (FIX: employee_display_number required)
-- ================
INSERT INTO employee (
  employee_display_number,
  user_id,
  first_name,
  last_name,
  gender,
  status,
  hired_at
)
SELECT
  2000000 + row_number() OVER (ORDER BY u.username) AS employee_display_number,
  u.user_id,
  CASE
    WHEN u.username LIKE 'doctor%' THEN split_part(u.display_name, ' ', 2)
    WHEN u.username LIKE 'manager%' THEN 'Manager'
    WHEN u.username LIKE 'reception%' THEN 'Reception'
    ELSE split_part(u.display_name, ' ', 1)
  END AS first_name,
  CASE
    WHEN u.username LIKE 'doctor%' THEN split_part(u.display_name, ' ', 2)
    WHEN u.username LIKE 'manager%' THEN split_part(u.display_name, ' ', 2)
    WHEN u.username LIKE 'reception%' THEN split_part(u.display_name, ' ', 2)
    ELSE 'Staff'
  END AS last_name,
  0,
  0,
  CURRENT_DATE
FROM "dcms_user" u
WHERE u.username IN ('manager1','manager2','doctor1','doctor2','doctor3','reception1','reception2')
ON CONFLICT (employee_display_number) DO NOTHING;

-- ================
-- EMPLOYEE POSITIONS (primary role + extra ortho for one doctor)
-- ================
-- Primary positions
INSERT INTO employee_position (employee_id, position_id, is_primary)
SELECT e.employee_id, p.position_id, TRUE
FROM employee e
JOIN "dcms_user" u ON u.user_id = e.user_id
JOIN position p ON p.position_type =
  CASE
    WHEN u.username LIKE 'doctor%' THEN 'DOCTOR'
    WHEN u.username LIKE 'manager%' THEN 'MANAGER'
    WHEN u.username LIKE 'reception%' THEN 'RECEPTION'
    ELSE 'ADMIN'
  END
ON CONFLICT DO NOTHING;

-- Add ORTHO as a secondary position for doctor1
INSERT INTO employee_position (employee_id, position_id, is_primary)
SELECT e.employee_id, p.position_id, FALSE
FROM employee e
JOIN "dcms_user" u ON u.user_id = e.user_id
JOIN position p ON p.position_type = 'ORTHO'
WHERE u.username = 'doctor1'
ON CONFLICT DO NOTHING;

-- ================
-- PATIENTS (MORE!)
-- ================
-- Insert a bunch of patients; register_number is auto-generated by your seq
INSERT INTO patient (first_name, last_name, gender, status)
SELECT
  'Patient' || gs::text,
  'Demo' || gs::text,
  (gs % 3)::int,
  (gs % 3)::int
FROM generate_series(1, 30) gs;

-- ================
-- PHONE NUMBERS (MORE! + FIX UNION/LIMIT)
-- Each patient gets 1-2 phones; primary enforced by code
-- ================
-- Primary phone per patient
INSERT INTO phone_number (patient_id, phone_number, label, is_primary)
SELECT
  p.patient_id,
  '+97699' || lpad((100000 + (row_number() OVER (ORDER BY p.created_at))::int)::text, 6, '0'),
  'Self',
  TRUE
FROM patient p
ORDER BY p.created_at
LIMIT 30;

-- Secondary phone for first 10 patients
INSERT INTO phone_number (patient_id, phone_number, label, is_primary)
SELECT *
FROM (
  SELECT
    p.patient_id,
    '+97688' || lpad((200000 + (row_number() OVER (ORDER BY p.created_at))::int)::text, 6, '0') AS phone_number,
    'Family' AS label,
    FALSE AS is_primary
  FROM patient p
  ORDER BY p.created_at
  LIMIT 10
) t;

-- ================
-- SMS HISTORY (MORE!)
-- ================
-- Create ~3 SMS for each of first 15 phone numbers
INSERT INTO sms (phone_number_id, direction, sent_at, subject, sms_text, note)
SELECT
  pn.phone_number_id,
  (gs % 2)::int,
  now() - (gs || ' hours')::interval,
  NULL,
  CASE
    WHEN (gs % 2)=1 THEN 'Appointment reminder'
    ELSE 'Patient replied: OK'
  END,
  NULL
FROM (
  SELECT phone_number_id
  FROM phone_number
  ORDER BY created_at
  LIMIT 15
) pn
CROSS JOIN generate_series(1, 3) gs;

-- ================
-- SERVICES (extra)
-- ================
INSERT INTO service_catalog
(service_type, display_number, display_name, default_duration_min, price_cents)
VALUES
  ('SURGERY', 4, 'Tooth Extraction', 45, 8000),
  ('CLEAN',   5, 'Teeth Cleaning',   30, 2500),
  ('XRAY',    6, 'Dental X-Ray',     10, 1500),
  ('WHITEN',  7, 'Teeth Whitening',  60, 12000)
ON CONFLICT (service_type) DO NOTHING;
